# Modified version of file from Domic project (see NOTICE).

language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
    - android-27
    - android-16
    - tools
    - platform-tools

jdk:
  - oraclejdk8

# Prevent Travis from running automatic project install.
install:
  - echo "Travis install step is noop"

script:
  - ci/build.sh

before_cache:
  - rm -f "$HOME"/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

notifications:
  email: false
